#spring.datasource.url=jdbc:mysql://mysql:3306/todo
#spring.datasource.username=todo_user
#spring.datasource.password=todo_pass
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#server.port=9090

# Database Configuration
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:todo}

spring.datasource.username=${DB_USER:root}

spring.datasource.password=${DB_PASS:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# Application Port
server.port=${APP_PORT:9090}
